import { PrismaClient } from "@prisma/client"

const prisma = new PrismaClient()

async function seedAllProducts() {
  console.log("🌱 Agregando TODOS los productos a la base de datos...")

  try {
    // Limpiar productos existentes
    await prisma.orderItem.deleteMany()
    await prisma.cartItem.deleteMany()
    await prisma.favorite.deleteMany()
    await prisma.review.deleteMany()
    await prisma.productSize.deleteMany()
    await prisma.productColor.deleteMany()
    await prisma.productImage.deleteMany()
    await prisma.product.deleteMany()

    // PRODUCTOS DE HOMBRE
    const hombresProducts = [
      {
        id: "prod_botin_guante",
        name: "Botín Dallas Cuero 35640 Hombre",
        slug: "botin-dallas-cuero-hombre",
        description: "Botín de cuero genuino para hombre, cómodo y resistente",
        price: 55990,
        originalPrice: 69990,
        discount: 20,
        sku: "GUA-35640",
        stock: 25,
        categoryId: "cat_hombre",
        brandId: "brand_guante",
        isFeatured: true,
        rating: 5.0,
        reviewCount: 0,
        images: ["/images/zapato-botin-marron.png"],
        colors: ["negro", "café"],
      },
      {
        id: "prod_zapato_caterpillar",
        name: "Zapato Deportivo Urbano Negro",
        slug: "zapato-deportivo-urbano-negro",
        description: "Zapato deportivo urbano con tecnología Cat",
        price: 55990,
        originalPrice: 69990,
        discount: 20,
        sku: "CAT-URB-001",
        stock: 30,
        categoryId: "cat_hombre",
        brandId: "brand_caterpillar",
        isFeatured: true,
        rating: 4.8,
        reviewCount: 12,
        images: ["/images/zapato-deportivo-negro.png"],
        colors: ["negro", "gris"],
      },
      {
        id: "prod_bota_panama",
        name: "Bota Outdoor Cuero Negro",
        slug: "bota-outdoor-cuero-negro",
        description: "Bota outdoor resistente al agua",
        price: 44990,
        originalPrice: 73990,
        discount: 39,
        sku: "PJ-OUT-001",
        stock: 15,
        categoryId: "cat_hombre",
        brandId: "brand_panama_jack",
        isFeatured: true,
        rating: 4.5,
        reviewCount: 8,
        images: ["/images/bota-negra-outdoor.png"],
        colors: ["negro"],
      },
      {
        id: "hombre_4",
        name: "Botín Casual Lodge Chukka Negro",
        slug: "botin-casual-lodge-chukka-negro",
        description: "Botín casual elegante para uso diario",
        price: 104990,
        originalPrice: 149990,
        discount: 30,
        sku: "FLO-CHU-001",
        stock: 20,
        categoryId: "cat_hombre",
        brandId: "brand_florsheim",
        isFeatured: false,
        rating: 4.7,
        reviewCount: 15,
        images: ["/images/botin-negro-cuero-formal.png"],
        colors: ["negro"],
      },
      {
        id: "hombre_5",
        name: "Bota Clásica 6-Inch Premium Camel",
        slug: "bota-clasica-6-inch-premium-camel",
        description: "Bota clásica Timberland resistente y cómoda",
        price: 89990,
        originalPrice: 119990,
        discount: 25,
        sku: "TIM-6IN-001",
        stock: 18,
        categoryId: "cat_hombre",
        brandId: "brand_timberland",
        isFeatured: false,
        rating: 4.9,
        reviewCount: 32,
        images: ["/images/bota-timberland-camel.png"],
        colors: ["camel", "miel"],
      },
      {
        id: "hombre_6",
        name: "Zapatilla Outdoor Hiking Beige",
        slug: "zapatilla-outdoor-hiking-beige",
        description: "Zapatilla técnica para senderismo y outdoor",
        price: 67990,
        originalPrice: 89990,
        discount: 24,
        sku: "MER-HIK-001",
        stock: 22,
        categoryId: "cat_hombre",
        brandId: "brand_merrell",
        isFeatured: false,
        rating: 4.6,
        reviewCount: 18,
        images: ["/images/zapatilla-outdoor-beige.png"],
        colors: ["beige", "caqui"],
      },
      {
        id: "hombre_7",
        name: "Zapatilla Hiking Técnica Negra",
        slug: "zapatilla-hiking-tecnica-negra",
        description: "Zapatilla técnica para montañismo",
        price: 79990,
        originalPrice: 109990,
        discount: 27,
        sku: "SAL-HIK-001",
        stock: 16,
        categoryId: "cat_hombre",
        brandId: "brand_salomon",
        isFeatured: false,
        rating: 4.8,
        reviewCount: 24,
        images: ["/images/zapatilla-hiking-negra.png"],
        colors: ["negro", "gris"],
      },
      {
        id: "hombre_8",
        name: "Zapatilla Deportiva Outdoor Negra",
        slug: "zapatilla-deportiva-outdoor-negra",
        description: "Zapatilla deportiva para actividades al aire libre",
        price: 59990,
        originalPrice: 79990,
        discount: 25,
        sku: "COL-OUT-001",
        stock: 25,
        categoryId: "cat_hombre",
        brandId: "brand_columbia",
        isFeatured: false,
        rating: 4.4,
        reviewCount: 11,
        images: ["/images/zapatilla-deportiva-negra-gris.png"],
        colors: ["negro", "gris"],
      },
      {
        id: "hombre_9",
        name: "Bota Montaña Cuero Marrón Premium",
        slug: "bota-montana-cuero-marron-premium",
        description: "Bota de montaña premium resistente al agua",
        price: 94990,
        originalPrice: 129990,
        discount: 27,
        sku: "PJ-MON-001",
        stock: 12,
        categoryId: "cat_hombre",
        brandId: "brand_panama_jack",
        isFeatured: false,
        rating: 4.7,
        reviewCount: 19,
        images: ["/images/bota-panama-jack-marron.png"],
        colors: ["marrón", "negro"],
      },
      {
        id: "hombre_10",
        name: "Zapatilla Trail Running Azul Técnica",
        slug: "zapatilla-trail-running-azul-tecnica",
        description: "Zapatilla técnica para trail running",
        price: 84990,
        originalPrice: 114990,
        discount: 26,
        sku: "TNF-TRA-001",
        stock: 14,
        categoryId: "cat_hombre",
        brandId: "brand_north_face",
        isFeatured: false,
        rating: 4.6,
        reviewCount: 14,
        images: ["/images/zapatilla-trail-azul-naranja.png"],
        colors: ["azul", "naranja"],
      },
    ]

    // PRODUCTOS DE MUJER
    const mujerProducts = [
      {
        id: "mujer_1",
        name: "Zapatos de Tacón Alto Vino Mujer",
        slug: "zapatos-tacon-alto-vino-mujer",
        description: "Zapatos elegantes de tacón alto para ocasiones especiales",
        price: 52990,
        originalPrice: 74990,
        discount: 29,
        sku: "MOD-TAC-001",
        stock: 15,
        categoryId: "cat_mujer",
        brandId: "brand_modare",
        isFeatured: false,
        rating: 4.6,
        reviewCount: 12,
        images: ["/images/zapato-tacon-vino.png"],
        colors: ["vino", "negro"],
      },
      {
        id: "mujer_2",
        name: "Zapatos Planos con Ojales Negro",
        slug: "zapatos-planos-ojales-negro",
        description: "Zapatos planos cómodos con detalles de ojales",
        price: 38990,
        originalPrice: 54990,
        discount: 29,
        sku: "PIC-PLA-001",
        stock: 20,
        categoryId: "cat_mujer",
        brandId: "brand_piccadilly",
        isFeatured: false,
        rating: 4.3,
        reviewCount: 8,
        images: ["/images/zapato-plano-negro-ojales.png"],
        colors: ["negro"],
      },
      {
        id: "mujer_3",
        name: "Botas Altas Cuero Negro con Hebilla",
        slug: "botas-altas-cuero-negro-hebilla",
        description: "Botas altas de cuero con hebilla decorativa",
        price: 67990,
        originalPrice: 89990,
        discount: 24,
        sku: "BAT-BOT-001",
        stock: 18,
        categoryId: "cat_mujer",
        brandId: "brand_bata",
        isFeatured: false,
        rating: 4.7,
        reviewCount: 15,
        images: ["/images/bota-alta-negra-hebilla.png"],
        colors: ["negro", "café"],
      },
      {
        id: "mujer_4",
        name: "Zapatillas Deportivas Azul Mujer",
        slug: "zapatillas-deportivas-azul-mujer",
        description: "Zapatillas deportivas cómodas para uso diario",
        price: 59990,
        originalPrice: 79990,
        discount: 25,
        sku: "ADI-DEP-001",
        stock: 25,
        categoryId: "cat_mujer",
        brandId: "brand_adidas",
        isFeatured: false,
        rating: 4.8,
        reviewCount: 22,
        images: ["/images/zapatilla-adidas-azul.png"],
        colors: ["azul", "blanco"],
      },
      {
        id: "mujer_5",
        name: "Zapatillas Outdoor Azul Marino",
        slug: "zapatillas-outdoor-azul-marino",
        description: "Zapatillas outdoor resistentes para actividades al aire libre",
        price: 72990,
        originalPrice: 99990,
        discount: 27,
        sku: "COL-OUT-002",
        stock: 16,
        categoryId: "cat_mujer",
        brandId: "brand_columbia",
        isFeatured: false,
        rating: 4.5,
        reviewCount: 10,
        images: ["/images/zapatilla-outdoor-azul.png"],
        colors: ["azul", "gris"],
      },
      {
        id: "mujer_6",
        name: "Zapatillas Blancas Clásicas Mujer",
        slug: "zapatillas-blancas-clasicas-mujer",
        description: "Zapatillas clásicas blancas versátiles",
        price: 54990,
        originalPrice: 74990,
        discount: 27,
        sku: "ADI-CLA-001",
        stock: 30,
        categoryId: "cat_mujer",
        brandId: "brand_adidas",
        isFeatured: false,
        rating: 4.9,
        reviewCount: 28,
        images: ["/images/zapatilla-adidas-blanca.png"],
        colors: ["blanco", "gris"],
      },
      {
        id: "mujer_7",
        name: "Zapatos de Tacón Vino con Correa",
        slug: "zapatos-tacon-vino-correa",
        description: "Zapatos elegantes con correa en el tobillo",
        price: 79990,
        originalPrice: 109990,
        discount: 27,
        sku: "CLA-TAC-001",
        stock: 12,
        categoryId: "cat_mujer",
        brandId: "brand_clarks",
        isFeatured: false,
        rating: 4.5,
        reviewCount: 16,
        images: ["/images/zapato-tacon-vino-correa.png"],
        colors: ["vino", "negro"],
      },
      {
        id: "mujer_8",
        name: "Botín Chelsea Negro Cuero Premium",
        slug: "botin-chelsea-negro-cuero-premium",
        description: "Botín Chelsea de cuero premium con elásticos laterales",
        price: 89990,
        originalPrice: 119990,
        discount: 25,
        sku: "DRM-CHE-001",
        stock: 14,
        categoryId: "cat_mujer",
        brandId: "brand_dr_martens",
        isFeatured: false,
        rating: 4.8,
        reviewCount: 21,
        images: ["/images/botin-negro-chelsea.png"],
        colors: ["negro"],
      },
      {
        id: "mujer_9",
        name: "Bota de Invierno Negra con Peluche",
        slug: "bota-invierno-negra-peluche",
        description: "Bota de invierno cálida con forro de peluche",
        price: 94990,
        originalPrice: 129990,
        discount: 27,
        sku: "SOR-INV-001",
        stock: 10,
        categoryId: "cat_mujer",
        brandId: "brand_sorel",
        isFeatured: false,
        rating: 4.7,
        reviewCount: 13,
        images: ["/images/bota-invierno-negra-peluche.png"],
        colors: ["negro", "gris"],
      },
      {
        id: "mujer_10",
        name: "Bota Camel Cómoda con Botón Decorativo",
        slug: "bota-camel-comoda-boton-decorativo",
        description: "Bota cómoda estilo UGG con botón decorativo",
        price: 119990,
        originalPrice: 159990,
        discount: 25,
        sku: "UGG-CAM-001",
        stock: 8,
        categoryId: "cat_mujer",
        brandId: "brand_ugg",
        isFeatured: false,
        rating: 4.9,
        reviewCount: 35,
        images: ["/images/bota-ugg-camel-boton.png"],
        colors: ["camel", "beige"],
      },
    ]

    // PRODUCTOS INFANTILES
    const infantilProducts = [
      {
        id: "prod_capitan_america",
        name: "Zapatillas Capitán América Infantil",
        slug: "zapatillas-capitan-america-infantil",
        description: "Zapatillas con diseño del Capitán América",
        price: 35990,
        originalPrice: 49990,
        discount: 28,
        sku: "MAR-CAP-001",
        stock: 20,
        categoryId: "cat_infantil",
        brandId: "brand_marvel",
        isFeatured: true,
        rating: 4.8,
        reviewCount: 15,
        images: ["/images/zapatilla-capitan-america.png"],
        colors: ["azul", "rojo", "blanco"],
      },
      {
        id: "infantil_2",
        name: "Zapatillas Spider-Man Botín Infantil",
        slug: "zapatillas-spiderman-botin-infantil",
        description: "Botín deportivo con diseño de Spider-Man",
        price: 42990,
        originalPrice: 59990,
        discount: 28,
        sku: "MAR-SPI-001",
        stock: 18,
        categoryId: "cat_infantil",
        brandId: "brand_marvel",
        isFeatured: false,
        rating: 4.6,
        reviewCount: 12,
        images: ["/images/zapatilla-spiderman-botin.png"],
        colors: ["negro", "rojo"],
      },
      {
        id: "infantil_3",
        name: "Zapatillas Deportivas Infantil",
        slug: "zapatillas-deportivas-bubble-gummers",
        description: "Zapatillas cómodas para niños",
        price: 29990,
        originalPrice: 39990,
        discount: 25,
        sku: "BG-DEP-001",
        stock: 25,
        categoryId: "cat_infantil",
        brandId: "brand_bubble_gummers",
        isFeatured: false,
        rating: 4.5,
        reviewCount: 8,
        images: ["/images/zapatilla-bubble-gummers.png"],
        colors: ["gris", "amarillo"],
      },
      {
        id: "infantil_4",
        name: "Zapatillas Spider-Man Azul Infantil",
        slug: "zapatillas-spiderman-azul-infantil",
        description: "Zapatillas Spider-Man en color azul",
        price: 38990,
        originalPrice: 54990,
        discount: 29,
        sku: "MAR-SPI-002",
        stock: 22,
        categoryId: "cat_infantil",
        brandId: "brand_marvel",
        isFeatured: false,
        rating: 4.7,
        reviewCount: 10,
        images: ["/images/zapatilla-spiderman-azul.png"],
        colors: ["azul", "rojo"],
      },
      {
        id: "infantil_5",
        name: "Zapatillas Deportivas Azul Marino",
        slug: "zapatillas-deportivas-azul-marino",
        description: "Zapatillas deportivas Nike para niños",
        price: 45990,
        originalPrice: 64990,
        discount: 29,
        sku: "NIK-DEP-001",
        stock: 20,
        categoryId: "cat_infantil",
        brandId: "brand_nike",
        isFeatured: false,
        rating: 4.3,
        reviewCount: 6,
        images: ["/images/zapatilla-azul-marino.png"],
        colors: ["azul"],
      },
      {
        id: "infantil_6",
        name: "Zapatillas Blancas con Detalles Neón",
        slug: "zapatillas-blancas-detalles-neon",
        description: "Zapatillas Adidas con detalles neón",
        price: 52990,
        originalPrice: 74990,
        discount: 29,
        sku: "ADI-NEO-001",
        stock: 18,
        categoryId: "cat_infantil",
        brandId: "brand_adidas",
        isFeatured: false,
        rating: 4.9,
        reviewCount: 20,
        images: ["/images/zapatilla-blanca-neon.png"],
        colors: ["blanco", "negro", "verde"],
      },
      {
        id: "infantil_7",
        name: "Zapatillas Azul con Verde Neón",
        slug: "zapatillas-azul-verde-neon",
        description: "Zapatillas Puma con colores vibrantes",
        price: 41990,
        originalPrice: 59990,
        discount: 30,
        sku: "PUM-VIB-001",
        stock: 16,
        categoryId: "cat_infantil",
        brandId: "brand_puma",
        isFeatured: false,
        rating: 4.4,
        reviewCount: 14,
        images: ["/images/zapatilla-azul-verde.png"],
        colors: ["azul", "verde"],
      },
      {
        id: "infantil_8",
        name: "Zapatillas Negras Suela Marrón",
        slug: "zapatillas-negras-suela-marron",
        description: "Zapatillas Converse clásicas",
        price: 33990,
        originalPrice: 47990,
        discount: 29,
        sku: "CON-CLA-001",
        stock: 24,
        categoryId: "cat_infantil",
        brandId: "brand_converse",
        isFeatured: false,
        rating: 4.6,
        reviewCount: 9,
        images: ["/images/zapatilla-negra-suela-marron.png"],
        colors: ["negro", "marrón"],
      },
      {
        id: "infantil_9",
        name: "Zapatillas Blancas Clásicas",
        slug: "zapatillas-blancas-clasicas",
        description: "Zapatillas Fila clásicas blancas",
        price: 28990,
        originalPrice: 39990,
        discount: 27,
        sku: "FIL-CLA-001",
        stock: 26,
        categoryId: "cat_infantil",
        brandId: "brand_fila",
        isFeatured: false,
        rating: 4.5,
        reviewCount: 11,
        images: ["/images/zapatilla-blanca-clasica.png"],
        colors: ["blanco"],
      },
      {
        id: "infantil_10",
        name: "Zapatillas Deportivas Rosa Niña",
        slug: "zapatillas-deportivas-rosa-nina",
        description: "Zapatillas Nike deportivas para niña",
        price: 47990,
        originalPrice: 67990,
        discount: 29,
        sku: "NIK-ROS-001",
        stock: 15,
        categoryId: "cat_infantil",
        brandId: "brand_nike",
        isFeatured: false,
        rating: 4.7,
        reviewCount: 18,
        images: ["/images/zapatilla-nike-rosa-infantil.png"],
        colors: ["rosa", "blanco"],
      },
    ]

    // Crear marcas adicionales que faltan
    const additionalBrands = [
      { id: "brand_modare", name: "Modare", slug: "modare", description: "Calzado femenino elegante", isActive: true },
      {
        id: "brand_piccadilly",
        name: "Piccadilly",
        slug: "piccadilly",
        description: "Zapatos cómodos para mujer",
        isActive: true,
      },
      { id: "brand_bata", name: "Bata", slug: "bata", description: "Calzado clásico y confiable", isActive: true },
      {
        id: "brand_timberland",
        name: "Timberland",
        slug: "timberland",
        description: "Botas outdoor premium",
        isActive: true,
      },
      { id: "brand_merrell", name: "Merrell", slug: "merrell", description: "Calzado técnico outdoor", isActive: true },
      {
        id: "brand_salomon",
        name: "Salomon",
        slug: "salomon",
        description: "Equipamiento deportivo técnico",
        isActive: true,
      },
      {
        id: "brand_columbia",
        name: "Columbia",
        slug: "columbia",
        description: "Ropa y calzado outdoor",
        isActive: true,
      },
      {
        id: "brand_north_face",
        name: "The North Face",
        slug: "north-face",
        description: "Equipamiento outdoor premium",
        isActive: true,
      },
      { id: "brand_clarks", name: "Clarks", slug: "clarks", description: "Calzado británico clásico", isActive: true },
      {
        id: "brand_dr_martens",
        name: "Dr. Martens",
        slug: "dr-martens",
        description: "Botas icónicas británicas",
        isActive: true,
      },
      { id: "brand_sorel", name: "Sorel", slug: "sorel", description: "Botas de invierno canadienses", isActive: true },
      { id: "brand_ugg", name: "UGG", slug: "ugg", description: "Botas cómodas australianas", isActive: true },
    ]

    // Crear marcas adicionales
    for (const brand of additionalBrands) {
      await prisma.brand.upsert({
        where: { id: brand.id },
        update: brand,
        create: brand,
      })
    }

    // Crear todos los productos
    const allProducts = [...hombresProducts, ...mujerProducts, ...infantilProducts]

    for (const productData of allProducts) {
      const { images, colors, ...product } = productData

      // Crear producto
      const createdProduct = await prisma.product.create({
        data: product,
      })

      // Crear imágenes
      for (let i = 0; i < images.length; i++) {
        await prisma.productImage.create({
          data: {
            id: `img_${createdProduct.id}_${i + 1}`,
            productId: createdProduct.id,
            url: images[i],
            altText: `${createdProduct.name} - Imagen ${i + 1}`,
            isPrimary: i === 0,
            order: i + 1,
          },
        })
      }

      // Crear colores
      for (const color of colors) {
        await prisma.productColor.create({
          data: {
            id: `color_${createdProduct.id}_${color}`,
            productId: createdProduct.id,
            name: color,
            hexCode: getColorHex(color),
          },
        })
      }

      // Crear tallas básicas
      const sizes =
        product.categoryId === "cat_infantil"
          ? ["24", "25", "26", "27", "28", "29", "30", "31", "32"]
          : ["38", "39", "40", "41", "42", "43", "44"]

      for (const size of sizes) {
        await prisma.productSize.create({
          data: {
            id: `size_${createdProduct.id}_${size}`,
            productId: createdProduct.id,
            size,
            stock: Math.floor(Math.random() * 10) + 1,
          },
        })
      }
    }

    console.log(`✅ Se crearon ${allProducts.length} productos exitosamente!`)
    console.log("📦 Productos por categoría:")
    console.log(`   👨 Hombre: ${hombresProducts.length}`)
    console.log(`   👩 Mujer: ${mujerProducts.length}`)
    console.log(`   👶 Infantil: ${infantilProducts.length}`)
  } catch (error) {
    console.error("❌ Error al crear productos:", error)
  } finally {
    await prisma.$disconnect()
  }
}

function getColorHex(color: string): string {
  const colorMap: { [key: string]: string } = {
    negro: "#000000",
    blanco: "#FFFFFF",
    café: "#8B4513",
    marrón: "#8B4513",
    azul: "#0066CC",
    rojo: "#FF0000",
    verde: "#00AA00",
    amarillo: "#FFFF00",
    gris: "#808080",
    vino: "#722F37",
    camel: "#C19A6B",
    beige: "#F5F5DC",
    rosa: "#FFC0CB",
    naranja: "#FFA500",
    miel: "#FFB347",
    caqui: "#F0E68C",
  }
  return colorMap[color.toLowerCase()] || "#808080"
}

seedAllProducts()
